server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api-v1.0/ {
    proxy_pass https://fungry-xt5f.onrender.com/api-v1.0/;
    proxy_set_header Host fungry-xt5f.onrender.com;
    proxy_ssl_server_name on;
}

    location / {
        try_files $uri $uri/ /index.html;
    }
}