services:
  postgres:
    image: postgres:16
    container_name: fungry-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fungry
      POSTGRES_USER: fungry_user
      POSTGRES_PASSWORD: fungry_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: