
spring.datasource.url=jdbc:postgresql://localhost:5432/fungry
spring.datasource.username=fungry_user
spring.datasource.password=fungry_pass


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true