
stripe.secretKey=${stripeSecretKey}
stripe:
     webhook:
            secret:whsec_10f114fd6504096d0a26acd54884ff67a522811c6282689afc160cd0c3362a82
stripe.success-url=http://localhost:8080/success
stripe.cancel-url=http://localhost:8080/cancel

spring.datasource.url=jdbc:postgresql://localhost:5432/fungry
spring.datasource.username=fungry_user
spring.datasource.password=StrongPassword@123



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true