spring.application.name=fungry
server.port=${PORT:9080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true