spring.application.name=fungry
server.port=${PORT:9080}

spring.datasource.url=jdbc:postgresql://localhost:5432/fungry
spring.datasource.username=fungry_user
spring.datasource.password=fungry_pass
cors.allowed-origins=http://localhost:5173

#server.servlet.session.cookie.same-site=none
#server.servlet.session.cookie.secure=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true